#!/usr/bin/env bash
# ── CSS Bundler ──────────────────────────────────────────────────────────────
# Resolves all @import statements in style/main.css into a single flat CSS
# file (style/bundled.css) so that Trunk can ship it without relying on the
# browser to resolve @import chains at runtime.
#
# Why: Trunk copies CSS files to dist/ but does not follow @import paths.
#      In production (Docker/actix-files), only dist/ is served, so @import
#      references to connect-design-system/ would 404.
#
# Usage: ./bundle-css.sh              (from frontend/ directory)
#        ./bundle-css.sh --check      (verify connect-design-system exists)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

MAIN_CSS="style/main.css"
OUTPUT="style/bundled.css"
DS_ROOT="../connect-design-system"

# Verify design system clone exists
if [[ ! -d "$DS_ROOT/packages" ]]; then
    echo "ERROR: connect-design-system/ not found at '$DS_ROOT'"
    echo "Clone it:  git clone git@github.com:LEGO/connect-design-system.git ../connect-design-system"
    exit 1
fi

if [[ "${1:-}" == "--check" ]]; then
    echo "OK: connect-design-system found"
    exit 0
fi

echo "Bundling CSS: $MAIN_CSS → $OUTPUT"

# Resolve a single @import line to an absolute file path.
# Input: @import line text, directory of the file containing the import.
resolve_import() {
    local line="$1"
    local base_dir="$2"
    # Extract path from @import 'path' or @import "path" or @import url('path')
    local path
    path=$(echo "$line" | sed -E "s/@import[[:space:]]+(url\()?['\"]([^'\"]+)['\"](\))?;?/\2/")
    # Resolve relative to the containing file's directory
    echo "$(cd "$base_dir" && realpath "$path" 2>/dev/null || echo "")"
}

# Inline a CSS file, recursively resolving any @import statements it contains.
inline_css() {
    local file="$1"
    if [[ ! -f "$file" ]]; then
        echo "/* WARNING: Missing file: $file */" >&2
        echo "/* WARNING: Missing file: $file */"
        return
    fi
    local dir
    dir="$(dirname "$file")"
    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" =~ ^[[:space:]]*@import[[:space:]] ]]; then
            local resolved
            resolved=$(resolve_import "$line" "$dir")
            if [[ -n "$resolved" && -f "$resolved" ]]; then
                # Recursively inline the imported file
                inline_css "$resolved"
            else
                echo "/* WARNING: Could not resolve import: $line */"
                echo "$line"
            fi
        else
            echo "$line"
        fi
    done < "$file"
}

# Bundle everything
{
    echo "/* ── BUNDLED CSS ── Generated by bundle-css.sh — DO NOT EDIT ────────── */"
    echo "/* Source: $MAIN_CSS + connect-design-system tokens & components         */"
    echo ""
    inline_css "$MAIN_CSS"
} > "$OUTPUT"

LINES=$(wc -l < "$OUTPUT" | tr -d ' ')
echo "Done: $OUTPUT ($LINES lines)"
