server:
  host: 0.0.0.0
  port: 8080
  secret: "Very Secret"
  jwtsecret: "Very Secret"
  s3_key_id: ""
  s3_key_secret: ""
  git_version: ""

database:
  url: "postgres://actix:actix@localhost/actix"

pg:
  user: actix
  password: actix
  port: 5432
  dbname: actix
  pool_max_size: 30
